import streamlit as st

import utils
from pages import CONFIG
from src.generative_ai.image_generation import dall_e_image

page_config = utils.load_page_config(CONFIG, __file__)
for key, value in page_config.items():
    globals()[key] = value

logger = utils.CustomLogger(__file__)


def main():
    st.caption(
        body="Using OpenAI DALL·E, this app performs image creation based on a user prompt.",
        help="[DALL·E](https://openai.com/dall-e-2)",
        unsafe_allow_html=True,
    )

    utils.show_source_code(path="src/generative_ai/image_generation/dall_e.py")

    submitted = False
    with st.form(key="dall_e_form", clear_on_submit=True):
        prompt = st.text_input(label="Input prompt: ")
        centered = st.columns(3)[1]
        with centered:
            submitted = st.form_submit_button(
                label="Generate with DALL·E", use_container_width=True
            )
    st.subheader(body="Output", anchor=False)
    if submitted:
        with st.spinner("Generating image..."):
            image = dall_e_image(prompt=prompt)
        st.image(image=image, caption="Generated by DALL·E")
