import streamlit as st

import utils
from src.generative_ai.image_generation import dall_e_image

loader = utils.PageConfigLoader(__file__)
loader.set_page_config(globals())

logger = utils.CustomLogger(__file__)


def main():
    st.caption(
        body="Using OpenAI DALL·E, this app performs image creation based on a user prompt.",
        help="[DALL·E](https://openai.com/dall-e-2)",
        unsafe_allow_html=True,
    )

    utils.show_source_code(path="src/generative_ai/image_generation/dall_e.py")

    submitted = False
    with st.form(key="dall_e_form"):
        prompt = st.text_input(label="Input prompt: ")
        centered = st.columns(3)[1]
        with centered:
            submitted = st.form_submit_button(
                label="Generate with DALL·E", use_container_width=True
            )
    st.subheader(body="Output", anchor=False)
    if submitted:
        image = dall_e_image(prompt=prompt)
        st.image(image=image, caption=prompt, help="Generated by DALL·E")
